# Generated by Django 3.1.14 on 2023-02-20 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(01)\\d{9}$', message='Phone number must be entered in the format: 01999999999')]),
        ),
    ]
