# Generated by Django 3.1.14 on 2023-02-20 19:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('expensive', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='productquestion',
            old_name='parent',
            new_name='reply',
        ),
    ]
