# Generated by Django 3.1.14 on 2022-12-06 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partnumber', models.CharField(help_text='unique carpart number', max_length=20, primary_key=True, serialize=False, verbose_name='unique carpart number')),
                ('description', models.CharField(max_length=200)),
                ('archived', models.BooleanField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='images/default.jpg', null=True, upload_to='images')),
                ('specification', models.FileField(null=True, upload_to='documents')),
                ('price', models.IntegerField(null=True)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parts', to='catalog.supplier')),
            ],
            options={
                'verbose_name_plural': 'parts',
                'ordering': ['partnumber'],
            },
            managers=[
                ('parts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(choices=[('BMW', 'bmw'), ('AUDI', 'audi'), ('LandRover', 'landrover')], max_length=50)),
                ('part', models.ManyToManyField(to='catalog.Part')),
            ],
        ),
    ]
