# Generated by Django 3.1.14 on 2022-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220915_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
