# Generated by Django 3.1.14 on 2022-09-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220915_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.supplier'),
        ),
    ]
