# Generated by Django 3.1.14 on 2022-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220915_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(default='carpart<django.db.models.fields.CharField>'),
        ),
    ]
