# Generated by Django 3.1.14 on 2022-09-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.SlugField(default=models.CharField(help_text='unique carpart number', max_length=20, primary_key=True, serialize=False, verbose_name='unique carpart number')),
        ),
    ]
