# Generated by Django 3.1.14 on 2022-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220921_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.SlugField(default='21-kk-jj'),
        ),
    ]
