# Generated by Django 3.1.14 on 2022-09-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220921_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='slug',
        ),
    ]
