# Generated by Django 3.1.14 on 2022-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_part_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='specification',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
