# Generated by Django 3.1.14 on 2022-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_part_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
