# Generated by Django 3.1.14 on 2022-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
